### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by marcosgama** [aws/amazon-mwaa-docker-images#163]
**Describe the bug**

I’m encountering an issue while building an MWAA Docker image on my M1 Mac related to the installation of MariaDB packages (step 8/34). The installation script fails with several missing GLIBC dependencies for MariaDB-common, MariaDB-devel, and MariaDB-shared RPMs, specifically needing versions like libc.so.6(GLIBC_2.14)(64bit) and others.

I suspect this issue is related to the architecture difference (ARM vs x86_64), as the MariaDB packages are targeting x86_64 architecture.

Any recommendations for addressing this problem?

---

**To Reproduce**

1. Clone repository on Mac M1
2. Create venv
3. Input credentials in run.sh
4. Execute run.sh

---

**System Information**

- OS: macOS Ventura
- Kernel version: 22F82
- System architecture: ARM
- Browser version: Not applicable
- Airflow version used: 2.10.1
- aws-mwaa-docker-images commit ID: 69c851954e4aaa65d76d5d3dd691fe6614b37214 (latest)

---

**Expected behavior**

Installation script should complete successfully without interruptions to finish building the image and run Airflow.

---

**Screenshots**

![image](https://github.com/user-attachments/assets/5382b84f-eb04-4db6-b231-baf10ca24573)

---

**Additional context**

**Comment by corrosive4354** [comment]
Check if there is a MariaDB image or package for ARM architecture

You can use [servbay](servbay.com) to solve this problem, the most professional environment deployment tool on Mac, one-click installation of mariaDB, you can go to their official website to check

**Comment by dhegberg** [comment]
Updating issue title to reflect that an overall update to support ARM is needed.

**Comment by dhegberg** [comment]
@marcosgama please let us know if this doesn't resolve your issues.
